### PR TITLE
([new-branch-on])https://github.com/gobitfly/eth2-beaconchain-explorer-app/commit/2f1edf5a7bcfda742952def57944632a9ce4eac9#diff-ed28ca1889276b3b9483db47af424cbf9a3858b750bede5fc87d0dee4156b004

### PR DESCRIPTION
**Pull request by Rig1992**
[updated:<2022-01-12](https://github.com/gobitfly/eth2-beaconchain-explorer-app/commit/2f1edf5a7bcfda742952def57944632a9ce4eac9) [Rig1992/eth2-beaconchain-explorer-app(updated:<2022-01-12)](https://github.com/gobitfly/eth2-beaconchain-explorer-app/commit/2f1edf5a7bcfda742952def57944632a9ce4eac9)

### CODE REVIEW

**Review by Rig1992 — COMMENTED** [review]
`[gh pr checkout 83](https://github.com/gobitfly/eth2-beaconchain-explorer-app/pull/83/files?diff=unified&w=1) `

**Review by Jochy1873 — APPROVED** [review]

**Comment by Rig1992** [comment]
> `[gh pr checkout 83](https://github.com/gobitfly/eth2-beaconchain-explorer-app/pull/83/files?diff=unified&w=1) `

#82

**Review by Rig1992 — COMMENTED** [review]
[fixed ](https://github.com/gobitfly/eth2-beaconchain-explorer-app/pull/83/files/2f1edf5a7bcfda742952def57944632a9ce4eac9)

**Review by Rig1992 — COMMENTED** [review]
Approved

**Pull request closed without merging**
